/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar um novo usuário */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realizar login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realizar logout */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter dados do usuário autenticado */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar solicitações com paginação e filtros */
        get: operations["SolicitacoesController_findAll"];
        put?: never;
        /** Criar uma nova solicitação */
        post: operations["SolicitacoesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter métricas e estatísticas do dashboard */
        get: operations["SolicitacoesController_getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter detalhes de uma solicitação por ID */
        get: operations["SolicitacoesController_getById"];
        put?: never;
        post?: never;
        /** Excluir uma solicitação */
        delete: operations["SolicitacoesController_delete"];
        options?: never;
        head?: never;
        /** Atualizar dados de uma solicitação */
        patch: operations["SolicitacoesController_update"];
        trace?: never;
    };
    "/solicitacoes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar status de uma solicitação */
        patch: operations["SolicitacoesController_updateStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        registerDto: {
            user: string;
            password: string;
        };
        loginDto: {
            user: string;
            password: string;
        };
        LoginResponseDto: {
            message: string;
            access_token: string;
        };
        LogoutResponseDto: {
            message: string;
        };
        MeResponseDto: {
            userId: string;
            name: string;
        };
        CriarSolicitacaoDto: {
            titulo: string;
            descricao: string;
            /** @enum {string} */
            categoria: "TI" | "RH" | "Compras" | "Financeiro" | "Infraestrutura";
        };
        SolicitacaoResponseDto: {
            /** Format: uuid */
            id: string;
            titulo: string;
            descricao: string;
            /** @enum {string} */
            categoria: "TI" | "RH" | "Compras" | "Financeiro" | "Infraestrutura";
            /** @enum {string} */
            status: "Aberto" | "Em Atendimento" | "Concluído";
            data_criacao: string;
            /** Format: uuid */
            usuario_id: string;
            solicitante: string[];
        };
        ListagemSolicitacoesResponseDto: {
            data: {
                /** Format: uuid */
                id: string;
                titulo: string;
                descricao: string;
                /** @enum {string} */
                categoria: "TI" | "RH" | "Compras" | "Financeiro" | "Infraestrutura";
                /** @enum {string} */
                status: "Aberto" | "Em Atendimento" | "Concluído";
                data_criacao: string;
                /** Format: uuid */
                usuario_id: string;
                solicitante: string | null;
            }[];
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        DashboardResponseDto: {
            total: number;
            abertas: number;
            emAtendimento: number;
            concluidas: number;
        };
        AtualizarSolicitacaoDto: {
            titulo?: string;
            descricao?: string;
            /** @enum {string} */
            categoria?: "TI" | "RH" | "Compras" | "Financeiro" | "Infraestrutura";
        };
        AlterarStatusSolicitacaoDto: {
            /** @enum {string} */
            status: "Aberto" | "Em Atendimento" | "Concluído";
        };
        ExcluirSolicitacaoResponseDto: {
            message: string;
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["registerDto"];
            };
        };
        responses: {
            /** @description Usuário registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["loginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                categoria?: "TI" | "RH" | "Compras" | "Financeiro" | "Infraestrutura";
                status?: "Aberto" | "Em Atendimento" | "Concluído";
                data_inicio?: string;
                data_fim?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListagemSolicitacoesResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarSolicitacaoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcluirSolicitacaoResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarSolicitacaoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoResponseDto"];
                };
            };
        };
    };
    SolicitacoesController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarStatusSolicitacaoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoResponseDto"];
                };
            };
        };
    };
}
